export const ELEMENT_LIBRARY_CATEGORIES = [
  'All',
  'Charts',
  'Badges & Pills',
  'Decorations',
  'UI Cards',
];
export const LIBRARY_ELEMENTS = [
  {
    id: 'lib_chart_bar',
    name: 'Bar Chart (Monthly Revenue)',
    category: 'Charts',
    type: 'chart',
    chartType: 'bar',
    width: 440,
    height: 280,
    fill: '#6366F1',
    cornerRadius: 16,
    chartData: [
      { label: 'Jan', value: 120 },
      { label: 'Feb', value: 180 },
      { label: 'Mar', value: 240 },
      { label: 'Apr', value: 210 },
      { label: 'May', value: 310 },
      { label: 'Jun', value: 390 },
    ],
  },
  {
    id: 'lib_chart_line',
    name: 'Line Chart (User Growth)',
    category: 'Charts',
    type: 'chart',
    chartType: 'line',
    width: 440,
    height: 280,
    fill: '#38BDF8',
    cornerRadius: 16,
    chartData: [
      { label: 'Mon', value: 45 },
      { label: 'Tue', value: 80 },
      { label: 'Wed', value: 65 },
      { label: 'Thu', value: 120 },
      { label: 'Fri', value: 160 },
      { label: 'Sat', value: 195 },
    ],
  },
  {
    id: 'lib_chart_pie',
    name: 'Donut Chart (Traffic Sources)',
    category: 'Charts',
    type: 'chart',
    chartType: 'donut',
    width: 320,
    height: 320,
    fill: '#A855F7',
    cornerRadius: 16,
    chartData: [
      { label: 'Direct', value: 45, color: '#6366F1' },
      { label: 'Organic', value: 30, color: '#38BDF8' },
      { label: 'Social', value: 15, color: '#EC4899' },
      { label: 'Referral', value: 10, color: '#10B981' },
    ],
  },
  {
    id: 'lib_badge_sale',
    name: 'Sale Tag Pill Badge',
    category: 'Badges & Pills',
    type: 'rounded_rect',
    width: 140,
    height: 36,
    cornerRadius: 18,
    fill: 'linear-gradient(135deg, #F43F5E, #FB923C)',
  },
  {
    id: 'lib_badge_verified',
    name: 'Verified Pro Badge',
    category: 'Badges & Pills',
    type: 'rounded_rect',
    width: 130,
    height: 32,
    cornerRadius: 16,
    fill: 'rgba(16, 185, 129, 0.15)',
    stroke: '#10B981',
    strokeWidth: 1,
  },
  {
    id: 'lib_card_glass',
    name: 'Glassmorphism Card Surface',
    category: 'UI Cards',
    type: 'rounded_rect',
    width: 340,
    height: 200,
    cornerRadius: 24,
    fill: '#131824',
    stroke: 'rgba(255, 255, 255, 0.08)',
    strokeWidth: 1,
    shadows: [{ x: 0, y: 16, blur: 32, color: 'rgba(0,0,0,0.5)' }],
  },
  {
    id: 'lib_glow_orb',
    name: 'Ambient Purple Glow Orb',
    category: 'Decorations',
    type: 'ellipse',
    width: 300,
    height: 300,
    fill: '#6366F1',
    opacity: 0.35,
    blur: 70,
  }
];