export const DEMO_PROJECTS = [
  {
    id: 'proj_flagship_studio',
    name: 'CryptoPay — Modern App',
    description: 'Modern Fintech mobile application with clean multi-page structure, glassmorphism cards, and interactive flows.',
    updatedAt: new Date().toISOString(),
    pages: [
      {
        id: 'page_welcome',
        name: 'Welcome Screen',
        background: '#09090B',
        elements: [
          {
            id: 'frame_welcome',
            name: 'Welcome Canvas',
            type: 'frame',
            x: 100,
            y: 80,
            width: 393,
            height: 852,
            fill: '#090D16',
            cornerRadius: 44,
            stroke: '#1E293B',
            strokeWidth: 2,
            opacity: 1,
            shadows: [{ x: 0, y: 20, blur: 40, color: 'rgba(0,0,0,0.6)' }],
            children: [
              {
                id: 'splash_glow',
                name: 'Glow Background',
                type: 'ellipse',
                x: 96,
                y: 120,
                width: 200,
                height: 200,
                fill: '#6366F1',
                opacity: 0.35,
                blur: 60,
              },
              {
                id: 'splash_logo_card',
                name: 'Logo Card',
                type: 'rounded_rect',
                x: 146,
                y: 180,
                width: 100,
                height: 100,
                cornerRadius: 28,
                fill: '#6366F1',
                shadows: [{ x: 0, y: 10, blur: 20, color: 'rgba(99,102,241,0.4)' }],
              },
              {
                id: 'splash_star_icon',
                name: 'Star Icon',
                type: 'star',
                x: 171,
                y: 205,
                width: 50,
                height: 50,
                fill: '#FFFFFF',
                points: 5,
                innerRadiusRatio: 0.5,
              },
              {
                id: 'splash_title',
                name: 'App Title',
                type: 'text',
                x: 36,
                y: 330,
                width: 320,
                height: 80,
                text: 'Future of Digital Finance',
                fontFamily: 'Inter',
                fontSize: 32,
                fontWeight: 800,
                fill: '#F8FAFC',
                textAlign: 'center',
                lineHeight: 1.2,
              },
              {
                id: 'splash_desc',
                name: 'Subtitle',
                type: 'text',
                x: 46,
                y: 430,
                width: 300,
                height: 50,
                text: 'Send, invest and exchange crypto worldwide with zero transaction fees.',
                fontFamily: 'Inter',
                fontSize: 14,
                fontWeight: 400,
                fill: '#94A3B8',
                textAlign: 'center',
                lineHeight: 1.5,
              },
              {
                id: 'btn_get_started',
                name: 'CTA Button',
                type: 'rounded_rect',
                x: 41,
                y: 690,
                width: 310,
                height: 56,
                cornerRadius: 28,
                fill: '#6366F1',
                shadows: [{ x: 0, y: 8, blur: 24, color: 'rgba(99,102,241,0.4)' }],
              },
              {
                id: 'btn_text_1',
                name: 'Button Label',
                type: 'text',
                x: 41,
                y: 708,
                width: 310,
                height: 24,
                text: 'Get Started →',
                fontFamily: 'Inter',
                fontSize: 16,
                fontWeight: 600,
                fill: '#FFFFFF',
                textAlign: 'center',
              }
            ]
          }
        ]
      },
      {
        id: 'page_dashboard',
        name: 'Wallet Dashboard',
        background: '#09090B',
        elements: [
          {
            id: 'frame_dashboard',
            name: 'Dashboard Canvas',
            type: 'frame',
            x: 100,
            y: 80,
            width: 393,
            height: 852,
            fill: '#0B0F19',
            cornerRadius: 44,
            stroke: '#1E293B',
            strokeWidth: 2,
            opacity: 1,
            shadows: [{ x: 0, y: 20, blur: 40, color: 'rgba(0,0,0,0.6)' }],
            children: [
              {
                id: 'dash_header_title',
                name: 'Header Title',
                type: 'text',
                x: 30,
                y: 60,
                width: 200,
                height: 24,
                text: 'Total Balance',
                fontFamily: 'Inter',
                fontSize: 14,
                fontWeight: 500,
                fill: '#94A3B8',
              },
              {
                id: 'dash_balance_val',
                name: 'Balance Amount',
                type: 'text',
                x: 30,
                y: 90,
                width: 330,
                height: 48,
                text: '$48,290.50',
                fontFamily: 'Inter',
                fontSize: 38,
                fontWeight: 800,
                fill: '#FFFFFF',
              },
              {
                id: 'dash_badge',
                name: 'Profit Badge',
                type: 'rounded_rect',
                x: 30,
                y: 150,
                width: 100,
                height: 28,
                cornerRadius: 14,
                fill: 'rgba(16, 185, 129, 0.15)',
                stroke: '#10B981',
                strokeWidth: 1,
              },
              {
                id: 'dash_badge_text',
                name: 'Badge Text',
                type: 'text',
                x: 40,
                y: 156,
                width: 80,
                height: 16,
                text: '+12.4% today',
                fontFamily: 'Inter',
                fontSize: 11,
                fontWeight: 600,
                fill: '#10B981',
              },
              {
                id: 'card_eth',
                name: 'ETH Card',
                type: 'rounded_rect',
                x: 30,
                y: 210,
                width: 333,
                height: 80,
                cornerRadius: 20,
                fill: '#131A29',
                stroke: '#1E293B',
                strokeWidth: 1,
              },
              {
                id: 'eth_title',
                name: 'ETH Title',
                type: 'text',
                x: 50,
                y: 230,
                width: 120,
                height: 20,
                text: 'Ethereum',
                fontFamily: 'Inter',
                fontSize: 16,
                fontWeight: 700,
                fill: '#FFFFFF',
              },
              {
                id: 'eth_amount',
                name: 'ETH Value',
                type: 'text',
                x: 220,
                y: 230,
                width: 120,
                height: 20,
                text: '$3,420.80',
                fontFamily: 'Inter',
                fontSize: 16,
                fontWeight: 700,
                fill: '#FFFFFF',
                textAlign: 'right',
              }
            ]
          }
        ]
      }
    ],
    prototypes: [
      {
        id: 'proto_1',
        fromElementId: 'btn_get_started',
        toFrameId: 'frame_dashboard',
        action: 'navigate',
        transition: 'smart_animate'
      }
    ],
    comments: [],
    components: {},
    styles: {}
  }
];