export const TOOLS = {
  SELECT: 'select',
  HAND: 'hand',
  FRAME: 'frame',
  RECTANGLE: 'rectangle',
  ROUNDED_RECT: 'rounded_rect',
  ELLIPSE: 'ellipse',
  TRIANGLE: 'triangle',
  POLYGON: 'polygon',
  STAR: 'star',
  LINE: 'line',
  ARROW: 'arrow',
  TEXT: 'text',
  PEN: 'pen',
  PENCIL: 'pencil',
  IMAGE: 'image',
  COMMENT: 'comment',
  ZOOM: 'zoom',
};
export const TOOL_ITEMS = [
  { id: TOOLS.SELECT, label: 'Select', shortcut: 'V', icon: 'MousePointer2', group: 'selection' },
  { id: TOOLS.HAND, label: 'Hand / Pan', shortcut: 'H', icon: 'Hand', group: 'selection' },
  { id: TOOLS.FRAME, label: 'Frame / Artboard', shortcut: 'F', icon: 'Frame', group: 'creation' },
  {
    id: TOOLS.RECTANGLE,
    label: 'Shapes',
    shortcut: 'R',
    icon: 'Square',
    group: 'creation',
    hasSubmenu: true,
    subtools: [
      { id: TOOLS.RECTANGLE, label: 'Rectangle', shortcut: 'R', icon: 'Square' },
      { id: TOOLS.ROUNDED_RECT, label: 'Rounded Rectangle', shortcut: 'U', icon: 'SquareRound' },
      { id: TOOLS.ELLIPSE, label: 'Ellipse / Circle', shortcut: 'O', icon: 'Circle' },
      { id: TOOLS.TRIANGLE, label: 'Triangle', shortcut: 'T', icon: 'Triangle' },
      { id: TOOLS.POLYGON, label: 'Polygon (Hexagon)', shortcut: 'Y', icon: 'Hexagon' },
      { id: TOOLS.STAR, label: 'Star', shortcut: 'S', icon: 'Star' },
      { id: TOOLS.LINE, label: 'Line', shortcut: 'L', icon: 'Minus' },
      { id: TOOLS.ARROW, label: 'Arrow', shortcut: 'Shift+L', icon: 'ArrowUpRight' },
    ]
  },
  { id: TOOLS.PEN, label: 'Pen Tool', shortcut: 'P', icon: 'PenTool', group: 'drawing' },
  { id: TOOLS.PENCIL, label: 'Pencil Tool', shortcut: 'Shift+P', icon: 'Pencil', group: 'drawing' },
  { id: TOOLS.TEXT, label: 'Text Tool', shortcut: 'T', icon: 'Type', group: 'creation' },
  { id: TOOLS.IMAGE, label: 'Upload Image', shortcut: 'Ctrl+I', icon: 'Image', group: 'media' },
  { id: TOOLS.COMMENT, label: 'Comment', shortcut: 'C', icon: 'MessageSquare', group: 'utility' },
];